export default {
  'The best service experts in town': 'Dịch vụ hàng đầu trong thành phố',
  'Order affordable high quality services like Beauty to your home!': 'Mang dịch vụ làm đẹp cấp cao giá thấp đến tận nhà bạn',
  'Beauty': 'Làm Đẹp',
  'Nail': 'Làm móng (Nail)',
  'Hair & Makeup': 'Làm tóc & Trang điểm',
  'How it works': 'Cách hoạt động',
  'Select services': 'Chọn dịch vụ',
  'Explore our list of services and select the ones you want': 'Khám phá và lựa chọn dịch vụ bạn mong muốn trong danh sách của chúng tôi',
  'Choose a suitable appointment date, time, and address': 'Chọn ngày, giờ, địa chỉ thích hợp cho cuộc hẹn',
  'Our experts come to you': 'Các chuyên gia sẽ có mặt',
  'Our experts will arrive at your address with everything needed to create your perfect look': 'Các chuyên gia của chúng tôi sẽ có mặt để giúp bạn có vẻ đẹp như ý',
  'Benefits': 'Lợi ích',
  'High Quality & Trusted Professionals': 'Chất lượng & Tin cậy',
  'We provide only verified, background checked and high quality professionals': 'Chúng tôi chỉ làm việc với các chuyên gia có danh tính, bằng cấp rõ ràng, và chất lượng',
  'Matched to Your Needs': 'Phù hợp với nhu cầu của bạn',
  'We match you with the right professionals with the right budget': 'Chúng tôi sẽ lựa chọn chuyên gia phù hợp nhất với nhu cầu của bạn',
  'Hassle Free Service Delivery': 'Nhẹ nhàng & Nhanh chóng',
  'Super convenient, guaranteed service from booking to delivery': 'Cực kì tiện lợi, đảm bảo dịch vụ tận nơi',
  'Are You A Professional Looking For New Customers?': 'Bạn là chuyên gia làm đẹp muốn mở rộng quy mô?',
  'Sign Up': 'Đăng ký ngay',

  'Choose the type of service': 'Chọn loại dịch vụ',
  'Choose your time-slot': 'Chọn thời gian',
  'From 10am - 5pm everyday': 'Từ 10 giờ sáng - 5 giờ chiều hàng ngày',
  'Our expert will get in touch with you soon': 'Chuyên viên của chúng tôi sẽ liên hệ với bạn',

  'Your selection': 'Bạn đã chọn',
  'What treatment do you need?': 'Bạn cần dịch vụ gì?',
  'Add': 'Chọn',
  'Next': 'Tiếp theo',

  'Enter your details': 'Điền thông tin',
  'Back': 'Quay lại',
  'Checkout': 'Thanh toán',
  'Pay': 'Xác nhận',
  'Facial': 'Da mặt',
  'Instructions': 'Hướng dẫn',
  'people book this last year': 'người đã đặt năm vừa qua',
  'Basic Facial cleaning + Spa': 'Làm sạch da mặt + Spa',
  'Fullname': 'Tên đầy đủ',
  'Phone': 'Số điện thoại',
  'Address': 'Địa chỉ',
  'What time works best for you': 'Chọn giờ phù hợp với bạn nhất',
  'Total': 'Tổng cộng',
  'Time': 'Thời gian',
  'today': 'hôm nay',

  'Your booking': 'Đơn hàng của bạn',
  'Booking Summary': 'Thông tin đơn hàng',
  'Payment method': 'Phương thức thanh toán',
  'Cash': 'Tiền mặt',
  'Credit Card (coming soon)': 'Thẻ tín dụng (coming soon)',
  'Confirm': 'Xác nhận',

  'Please wait...': 'Vui lòng chờ...',
  'Booking successful!': 'Đặt thành công!',
  'Home Page': 'Trang chủ',

  'Now just sit back and relax. Our provider will call you shortly to arrange the service.': 'Chuyên viên của chúng tôi sẽ liên hệ với bạn qua điện thoại trong thời gian sớm nhất.',
  'We will also message you the booking information in a few minutes': 'Xác nhận đơn hàng sẽ được gửi cho bạn ngay sau đây',
}